
// APP

export const UPDATE_LOGIN_STATUS = 'UPDATE_LOGIN_STATUS';

// REGISTER

export const UPDATE_REGISTER_AVATAR = 'UPDATE_REGISTER_AVATAR';
export const UPDATE_REGISTER_PSEUDO = 'UPDATE_REGISTER_PSEUDO';
export const UPDATE_REGISTER_EMAIL = 'UPDATE_REGISTER_EMAIL';
export const UPDATE_REGISTER_PASSWORD = 'UPDATE_REGISTER_PASSWORD';
export const UPDATE_REGISTER_PHONE = 'UPDATE_REGISTER_PHONE';
export const UPDATE_REGISTER_DESCRIPTION = 'UPDATE_REGISTER_DESCRIPTION';
export const UPDATE_REGISTER_BIRTHDAY = 'UPDATE_REGISTER_BIRTHDAY';

// LOGIN

export const UPDATE_LOGIN_PSEUDO = 'UPDATE_LOGIN_PSEUDO';
export const UPDATE_LOGIN_PASSWORD = 'UPDATE_LOGIN_PASSWORD';
